In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('my_database.db')

In [2]:
#Reading csv to dataframe
df = pd.read_csv('cleaned_dataset.csv')

In [3]:
df.to_sql(
    'direct_mail',      # table name
    conn,
    if_exists='replace',  # 'replace', 'append', or 'fail'
    index=False
)

50000

In [4]:
pd.read_sql('''
            SELECT
                COUNT(*) AS Total_mailers_sent,
                SUM(response_flag) AS Total_responses,
                SUM(acquisition_flag) AS Total_acquisitions,
                SUM(response_flag)*100.0 /COUNT(*) AS response_rate_pct,
                ROUND(SUM(acquisition_flag)*100.0 /COUNT(*),2) AS acquisition_rate_pct,
                SUM(mailing_cost_usd) AS total_mailing_cost,
                SUM(estimated_monthly_charge_volume_usd) AS total_charge_volume
            FROM
                direct_mail''',conn)

,Total_mailers_sent,Total_responses,Total_acquisitions,response_rate_pct,acquisition_rate_pct,total_mailing_cost,total_charge_volume
0,50000,1618,1040,3.236,2.08,97469.94,21499458.48

In [5]:

pd.read_sql('''
            SELECT
                offer_type,
                ROUND(SUM(response_flag)*100.0 /COUNT(*),2) AS response_rate,
                ROUND(SUM(acquisition_flag)*100.0 /COUNT(*),2) AS acquisition_rate,
                ROUND(AVG(roi),2) AS average_ROI,
                ROUND(SUM(estimated_monthly_charge_volume_usd)) AS total_charge_volume
            FROM
                direct_mail
            GROUP BY
                offer_type''',conn)

,offer_type,response_rate,acquisition_rate,average_ROI,total_charge_volume
0,0% Intro APR,4.54,3.02,5.15,6031133.0
1,Cash Back 2%,3.62,2.43,5.93,6196779.0
2,No Annual Fee,2.92,1.87,3.97,4116952.0
3,Rewards Points 3x,2.77,1.69,1.35,2435345.0
4,Travel Miles 2x,2.32,1.38,1.43,2719250.0

In [6]:
pd.read_sql('''
            SELECT
                region,
                offer_type,
                SUM(mailing_cost_usd) AS total_mailing_cost
            FROM
                direct_mail
            WHERE
                acquisition_flag=0
            GROUP BY
                region,
                offer_type
            ORDER BY
                total_mailing_cost DESC
            ''',conn)

       region         offer_type  total_mailing_cost
0     Midwest    Travel Miles 2x             4501.51
1        West    Travel Miles 2x             4442.68
2   Northeast    Travel Miles 2x             4435.06
3   Southwest    Travel Miles 2x             4428.60
4   Southeast    Travel Miles 2x             4419.65
5   Northeast  Rewards Points 3x             4212.56
6     Midwest  Rewards Points 3x             4209.49
7   Southwest  Rewards Points 3x             4164.44
8   Northeast       0% Intro APR             3973.70
9   Southeast  Rewards Points 3x             3936.13
10       West  Rewards Points 3x             3884.71
11  Southwest       0% Intro APR             3822.16
12  Southeast       0% Intro APR             3821.53
13    Midwest       0% Intro APR             3775.26
14       West       0% Intro APR             3692.71
15  Northeast       Cash Back 2%             3576.51
16    Midwest       Cash Back 2%             3543.03
17       West       Cash Back 2%             3485.25
18  Southeast       Cash Back 2%             3472.47
19  Southwest       Cash Back 2%             3414.73
20  Southwest      No Annual Fee             3345.49
21  Northeast      No Annual Fee             3339.78
22  Southeast      No Annual Fee             3203.50
23       West      No Annual Fee             3198.10
24    Midwest      No Annual Fee             3170.65